### ISSUE TITLE
[RFC] remove manifest dependency on server_environment_files

### ISSUE THREAD

**Issue by sbidoul** [OCA/server-env#10]
The manifest of `server_environment` declares a dependency on `server_environment_files`.

With tools such as [module_auto_update](https://github.com/OCA/server-tools/tree/11.0/module_auto_update) or [click-odoo-initdb](https://github.com/acsone/click-odoo-contrib#click-odoo-initdb-beta), small changes to server_environment_file (such as bumping a version number in a [web_environment_ribbon](https://github.com/OCA/web/tree/11.0/web_environment_ribbon) parameter) tend to trigger a large chain of unncessary updates for all modules that depend on `server_environment`.

In practice server_environment only relies on the presence of server_environment_files to locate the directory of configuration files. It's absence would be otherwise detected by `import odoo.addons.server_environment_files` failing during server startup.

Would there be any drawback to removing this dependency from the manifest?

**Comment by sbidoul** [comment]
Actually server_environment_file need not even be installed in the database for server_environment to work. Having it in addons_path (or sys.path) is enough.

@yvaucher @guewen @gurneyalex what do you think?

**Comment by guewen** [comment]
> Actually server_environment_file need not even be installed in the database for server_environment to work. Having it in addons_path (or sys.path) is enough.

100% agree to remove it from the dependencies in the manifest

**Comment by yvaucher** [comment]
As everything is merged this is resolved, thanks for it.

**Comment by ThomasBinsfeld** [comment]
Thanks :+1:
