### ISSUE TITLE
V13 server_environment_ir_config_parameter

### ISSUE THREAD

**Issue by leemannd** [OCA/server-env#43]
Hello,
Since V9, the module server_environment_ir_config_parameter has not the key _installable=True_ .
I'm just wondering if there is any reason I would not know -> https://github.com/OCA/server-env/blob/13.0/server_environment_ir_config_parameter/__manifest__.py#L12

**Comment by yvaucher** [comment]
@leemannd if this attribute is not set, by default it's `installable: True`

https://github.com/odoo/odoo/blob/13.0/odoo/modules/module.py#L312

`installable` key was added in a time we kept all modules in the new version branch and disabled all modules during a module migration.

**Comment by leemannd** [comment]
Thanks for the explanation
