### ISSUE TITLE
Odoo Critical error "failed to initialize database" once server_environemnt is installed

### ISSUE THREAD

**Issue by dreispt** [OCA/server-env#44]
```
server-env/server_environment/serv_config.py", line 50, in <module>
    "The parameter 'running_env' has not be set neither in base config "
Exception: The parameter 'running_env' has not be set neither in base config file option -c or in openerprc.
We strongly recommend against using the rc file but instead use an explicit config file with this content:
[options]
running_env = dev
```

I get the point that the additional configuration is very important.
But does it justify preventing the service from starting?
I think this would be a log message, rather than a error with a traceback.

**Comment by simahawk** [comment]
IMO we should default to `running_env=dev` + show a warning that is running in dev mode.
@guewen ?

**Comment by guewen** [comment]
I agree!

**Comment by amh-mw** [comment]
Per https://github.com/OCA/server-env/tree/13.0/server_environment#configuration
> Values associated to keys containing 'passw' are only displayed in the 'dev' environment.

I'm not sure that we should default to a setting that exposes passwords...

**Comment by dreispt** [comment]
I'm not sure what "displayed" means (printed out to the server log?), but following @amh-mw comment, I suggest using `test` as the default value, rather than `dev`..

**Comment by guewen** [comment]
IIRC, the module automatically replaces password fields with `*` chars in form views unless the running env is `dev`. This is a good remark @amh-mw, considering this, it would be better to use `test` by default indeed.

**Comment by simahawk** [comment]
ah, reading now these remarks... :sweat_smile: 
I'll update my PR then :)

**Comment by simahawk** [comment]
https://github.com/OCA/server-env/pull/45

**Comment by pedrobaeza** [comment]
I suppose this is the same error I have now in OCA/l10n-spain:

https://travis-ci.org/github/OCA/l10n-spain/jobs/670689281#L2437

Is it?
