### ISSUE TITLE
server_environment: Show warning even if it is not installed

### ISSUE THREAD

**Issue by moylop260** [OCA/server-env#56]
The module `server_environment` is checking if it is configured correctly:
 - https://github.com/OCA/server-env/blob/7d6ebde33349dadf1600a5ccf4e35982171864ff/server_environment/serv_config.py#L49-L60

Even if it is not installed.

The following PR:
 - https://github.com/OCA/account-financial-tools/pull/1057

It has github statuses in red because of this warning in runbot log.

IMHO the modules don't should be checked if it is correctly configured since that it is not installed.

It should be checked from a `hook` directly since it is executed only if the module is installed so the warning could be valid.

**Comment by oscarolar** [comment]
@simahawk and @alexey-pelykh what do you think?

**Comment by oscarolar** [comment]
Also v12 is running with warnings: https://runbot.odoo-community.org/runbot/build/3440004

**Comment by moylop260** [comment]
Fixed from https://github.com/OCA/server-env/pull/57
